services:
  - type: web
    name: yt-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    preBuildCommand: |
      apt-get update
      apt-get install -y ffmpeg
